#!/bin/sh

echo eth0 config Start......
/sbin/ifconfig lo 127.0.0.1
if [ -f /etc/init.d/eth0.config ] ; then
	source /etc/init.d/eth0.config

	if mount|grep -q "on / type nfs" ; then
		echo NFS working,pass network config...
	else
		echo network config by file...
		ifconfig eth0 down
		ifconfig eth0 hw ether $MAC
		ifconfig eth0 $IP netmask $Mask up
		route add default gw $Gateway
	fi

	echo nameserver $DNS > /etc/resolv.conf
else

	if mount|grep -q "on / type nfs" ; then
		echo NFS working,pass network config...
	else
		echo network config by default...
		/sbin/ifconfig eth0 192.168.1.240 netmask 255.255.255.0 up
	fi
fi

echo eth0 config Done
